### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by tdhung80** [devias-io/react-material-dashboard#4]
Hi,

Nice work, just a problem that it has to render whole root element every navigation.

My Bests,
Hung Tran

**Comment by devias-io** [comment]
Hi Hung Tran,

The root element is not re-rendered on each page navigation. You can check it by going into `src/App.jsx` and on top of the `<Router />` you can add a new component with innerHTML as `{Date.now()}` (_don't forget to wrap this component and the Router in a Fragment since the ThemeProvider expects one component only_). This will print the current timestamp. You will see that the timestamp is the same even if you change the current route. That timestamp should be updated only if the root component is re-rendered.

With the current implementation almost every page (view in our case) uses a layout (Dashboard) in its component render method. The reason why we decided to put the layout inside of the view, is that some views do not make use of it, such as login, sign up, not found, under development etc.

Each route navigation re-renders this layout since it is inside the view.  If you really need to stop this behaviour, then you could use two Routers in your project. One that acts as a top level, where you have the routes for the views that do not need that layout (such as login, sign up...), and then a route to a view that has another Router inside which has its own `<Switch />` with the routes that will use the layout. In this view you should wrap over the `<Switch />` component your layout. Then you should remove the DashboardLayout wrapper from each view to prevent double layout rendering.

Please let us know if this answers your question. Not sure if this is clear enough, but if you need an example, we will reply as soon as possible. 

Regards
