### ISSUE TITLE
Does this template support collapsing of sidebar in free or pro version?

### ISSUE THREAD

**Issue by parichay-front-end** [devias-io/react-material-dashboard#53]
Hi,
Thanks for an amazing dashboard template. Out team was thinking of using this in one of our projects. Wanted to know if this support's the feature of sidebar collapsing with a button, where only the icons are visible in sidebar(In Desktop view)
If not, is that feature available in the pro version?

**Comment by arobert93** [comment]
Hi @parichay-front-end! At this moment we do not have that functionality, but it can be easily integrated. Both projects, free or paid, have a specific component "NavItem". It can be adjusted to accept a new prop, "compact" (or something similar). While compact prop exists, you simply do not render the title. Also, the compact prop has to be attributed to the sidebar, so you can determine the width. Instead of having 320px (or current width size) you set 80px with overflow-x hidden. This should do the job.
